plugins:
  - name: java
    implementation: builtin:java
  - name: protoc-gen-go
    implementation: golang:protobuf:protoc-gen-go
    deps:
      - "@org_golang_google_protobuf//reflect/protoreflect"
      - "@org_golang_google_protobuf//runtime/protoimpl"
  - name: protoc-gen-go-grpc
    implementation: grpc:grpc-go:protoc-gen-go-grpc
    deps:
      - "@org_golang_google_grpc//:go_default_library"
      - "@org_golang_google_grpc//codes"
      - "@org_golang_google_grpc//status"
rules:
  - name: proto_compile
    implementation: stackb:rules_proto:proto_compile
    visibility:
      - "//visibility:public"
  - name: proto_go_library
    implementation: stackb:rules_proto:proto_go_library
    visibility:
      - //visibility:public
    resolves:
      - "google/protobuf/([a-z]+).proto @org_golang_google_protobuf//types/known/${1}pb"
      - "google/protobuf/(descriptor|plugin).proto @org_golang_google_protobuf//types/${1}pb"
languages:
  - name: java
    plugins:
      - java
    rules:
      - proto_compile
    enabled: true
  - name: go
    plugins:
      - protoc-gen-go
      - protoc-gen-go-grpc
    rules:
      - proto_compile
      - proto_go_library
    enabled: false